# Generated by Django 4.0.4 on 2022-04-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('paragraph', models.CharField(max_length=256)),
                ('game_link_text', models.CharField(max_length=256)),
                ('game_link_href', models.CharField(max_length=256)),
                ('choice_url', models.URLField()),
                ('is_redeemed', models.BooleanField()),
            ],
        ),
    ]
