# Generated by Django 4.0.4 on 2022-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='choice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_link_href',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_link_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_redeemed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='paragraph',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
