# Generated by Django 4.0.4 on 2022-04-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_unique title href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_link_href',
            field=models.URLField(blank=True, null=True),
        ),
    ]
