# Generated by Django 4.0.4 on 2022-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_game_drm_free_dl_links_game_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=128)),
                ('order_placed', models.CharField(max_length=32)),
                ('order_total', models.CharField(max_length=16)),
            ],
        ),
    ]
